### ISSUE TITLE
Linux/Wine: crash at start

### ISSUE THREAD

**Issue by legluondunet** [everalert/annodue#2]
Hello Galeforce, I own the GOG version and so far I use the swe1r-patcher mod mainly for HD fonts.
I extracted all the Annodue files to the main game folder, but the game crashes on launch.
Is there a way to generate an Annodue debug log?

**Comment by legluondunet** [comment]
Galeforce:

yo, great to hear the archive is good now.
right now there is no logging, it's been on the backburner since focusing on getting 0.1 out in time for tournament but i'm intending to get to it very soon.
for now you could try something like running [procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) or checking the windows event viewer for errors (i'm not sure what equivalent there might be on linux, sorry). it would also be helpful to know if there is either a tmp directory or settings.ini file in your annodue directory after the crash

**Comment by legluondunet** [comment]
There is a tmp directory wich contains "annodue.tmp.dll" file.  But no settings.ini file.

**Comment by everalert** [comment]
Hello there. I just published 0.1.3, which should now generate a crash log in `./annodue`. Please give it a try and send me the contents of the log.

**Comment by legluondunet** [comment]
Hello, just tried latest version, game still crashes but I found no log file available in annodue folder.

**Comment by everalert** [comment]
No worries, that does still narrow things down, thank you. I'll let you know whenever there is anything new to try.
